- repo: https://github.com/ambv/black
  rev: stable
  hooks:
      - id: black
        name: Format Python Code
        language: python
        entry: black
        args:
            - newreleases

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
      - id: flake8
        name: Flake8 Check
        language: python
        entry: flake8
        args:
            - newreleases

- repo: https://github.com/pycqa/pydocstyle
  rev: master
  hooks:
      - id: pydocstyle
        name: Python Documentation Style Check
        language: python
        entry: pydocstyle
        args:
            - newreleases

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: master
  hooks:
      - id: mypy
        args:
            - --ignore-missing-imports
